/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 xbox_controller_free.glb
Author: AT design studio (https://sketchfab.com/ANDRIANIAINAToky)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/xbox-controller-free-913641c8ac254ca8bbc182d69487ff45
Title: Xbox controller free
*/

import { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
	const { nodes, materials } = useGLTF('/xbox_controller_free.glb')
	return (
		<group {...props} dispose={null}>
			<group rotation={[-Math.PI / 2, 0, 0]}>
				<group position={[0, 0, -0.128]} rotation={[1.679, 0, 0]} scale={[-1, 1, 1]}>
					<mesh geometry={nodes.Controller_0.geometry} material={materials.White} />
					<mesh geometry={nodes.Controller_0_1.geometry} material={materials.White} />
					<mesh geometry={nodes.Controller_0_2.geometry} material={materials.White} />
					<mesh geometry={nodes.Controller_1.geometry} material={materials.Front_button_inserts} />
					<mesh geometry={nodes.Controller_2.geometry} material={materials.Direction} />
					<mesh geometry={nodes.Controller_2_1.geometry} material={materials.Direction} />
					<mesh geometry={nodes.Controller_3.geometry} material={materials.Texte} />
					<mesh geometry={nodes.Controller_4.geometry} material={materials.Yellow} />
					<mesh geometry={nodes.Controller_5.geometry} material={materials.material} />
					<mesh geometry={nodes.Controller_6.geometry} material={materials.Transparent} />
					<mesh geometry={nodes.Controller_7.geometry} material={materials.Analogs_color} />
					<mesh geometry={nodes.Controller_8.geometry} material={materials.white} />
					<mesh geometry={nodes.Controller_9.geometry} material={materials.Metal_bits} />
					<mesh geometry={nodes.Controller_10.geometry} material={materials.Logo_black} />
					<mesh geometry={nodes.Controller_11.geometry} material={materials.Blue} />
					<mesh geometry={nodes.Controller_12.geometry} material={materials.Green} />
				</group>
			</group>
		</group>
	)
}

useGLTF.preload('/xbox_controller_free.glb')
